# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'colbatechDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for colbatechDemo

  target 'colbatechDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'colbatechDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'

end
